REQ_ID = 1
CONNECT_TO_GAME = 2
RECONNECT_TO_GAME = 3
CREATE_NEW_ROOM = 4
START_GAME = 5
SEND_QUIZ_ANSWER = 6
PAUSE_GAME = 7
LEAVE_GAME = 8
NEXT_QUESTION = 9
BACK_TO_MENU = 10
SHOW_TABLE = 11

ERR = -1
